services:
    postgres:
        container_name: postgres
        image: postgres:17
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - 5432:${POSTGRES_PORT}
        volumes:
            - postgres_data:/var/lib/postgresql/data
    app:
        container_name: app
        build: .
        ports:
            - 3000:${APP_PORT}
        restart: always
        environment:
            DATABASE_URL: ${DATABASE_URL}
        depends_on:
            - postgres

volumes:
    postgres_data:
